// 共通関数
const FUNC_ID_LOGIN = "1";
const FUNC_ID_MAIN = "2";
const FUNC_ID_CSTREGIST_SEARCH = "3";
const FUNC_ID_CSTREGIST_RESULT = "4";
const FUNC_ID_CSTREGIST_INPUT = "5";
const FUNC_ID_CSTREGIST_CONFIRM = "6";
const FUNC_ID_CSTREGIST_COMPLETE = "7";
const FUNC_ID_APP_LIST = "8";
const FUNC_ID_APP_CONFIRM = "9";
const FUNC_ID_APP_COMPLETE = "10";
